### ISSUE TITLE
Include function to load temperature and humidity from our datalogging sensors

### ISSUE THREAD

**Issue by AndersBros** [NRCWE/NFA_Aerosol#6]
There is a function for it in the JT_Lib.py script, but it has to be checked and commented properly before it is added

**Comment by JesBL** [comment]
def Load_Fourtec(file, start=0, end=0):
    """
    Function to load data from a .csv datafile generated by the Fourtec
    bluefish and extract relevant data for plotting.
    
    Parameters
    ----------
    file : str
        Path to a .csv file generated by the Fourtec Datasuite program
    start : datetime, optional
        Specify starting time to plot by setting a datetime value e.g.
        datetime.datetime(2023,01,28,15,00,00). The default is 0.
    end : datetime, optional
        Specify end time to plot by setting a datetime value e.g.
        datetime.datetime(2023,01,28,15,00,00). The default is 0.
    Returns
    -------
    Data_return : numpy.array
        Array containing Temperature and relative humidity including a column
        of Datetime values for easy plotting.
    Header : list
        A list containing the header for all columns in the Data_return variable
    """
 
    
    Fourtec_Data = pd.read_csv(file, delimiter=',',skiprows=8,header=0,encoding="UTF-16")
    Fourtec_Datetime = Fourtec_Data["Date"].str.cat(Fourtec_Data["Time"],sep="\t")

    Fourtec_Datetime = np.array([datetime.strptime(i, "%d/%m/%Y\t %H:%M:%S") 
                                      for i in Fourtec_Datetime])

    # Select data within specified time interval if specified
    if (start != 0) or (end != 0):
        if (start != 0) & (end == 0):
            index = Fourtec_Datetime>start
        elif (start == 0) & (end != 0):
            index = Fourtec_Datetime<end
        else:
            index = (Fourtec_Datetime>start) & (Fourtec_Datetime<end)
        Fourtec_Datetime = Fourtec_Datetime[index]
        Fourtec_Data = Fourtec_Data[index]
        
    Fourtec_Data=Fourtec_Data[["Internal Digital Temperature","Internal RH"]]
    Fourtec_Data.insert(0, "Datetime", Fourtec_Datetime, True)
    Header = ["Datetime","Temperature","Relative humidity"]
    Data_return = np.array(Fourtec_Data)
    
    return Data_return, Header
